### ISSUE TITLE
Docker app?

### ISSUE THREAD

**Issue by KalebSchmidlkofer** [samcf/ogres#119]
Is there any way we will get a docker-compose or dockerfile anytime soon?

**Comment by samcf** [comment]
I'm happy to put together something like that, though my experience with Docker is limited. Can I ask what you would use it for? Just want to start up your own instance of the server easily?

Thanks for the question!

**Comment by KalebSchmidlkofer** [comment]
I'm running casaOS on a Zimaboard at the current time, and it uses docker to deploy apps, and I was.thinkomg this would be really fun to self host for my friends and family to play DND together.

**Comment by samcf** [comment]
Another contributor told me they'll take a shot at this. In the mean time https://ogres.app/ is free to use for all your games :)

**Comment by KalebSchmidlkofer** [comment]
Cool, thank you.
