### ISSUE TITLE
Firefox renders blank tokens

### ISSUE THREAD

**Issue by samcf** [samcf/ogres#137]
![Screenshot 2024-03-19 at 10 06 05 PM](https://github.com/samcf/ogres/assets/1691525/8ed10b98-cdcb-4e94-a0ba-a3ac3d080315)

**Comment by zanza00** [comment]
I did some digging and there is a circle on the token with radius of 38 (it has the class `scene-token-ring`) that obscure the token circle. I think that the default `fill` in firefox is `black` and not `transparent`

![image](https://github.com/samcf/ogres/assets/3732011/92f6c8fc-9a7e-462d-baed-26bfea9d1b60)
![image](https://github.com/samcf/ogres/assets/3732011/d8413d25-2fcc-4a24-8105-65dd2498b0ab)

(I am only a frontend dev that stumbled upon your app, hope this help)

**Comment by samcf** [comment]
Thanks for looking at this @zanza00! I think the issue is that Firefox has different rules for styling the shadow DOM. I made a change recently that predefined all the tokens with `<defs />` which I then `<use />` further down the tree. Chrome and Safari seem happy to apply styles to the `<use />`'d elements but Firefox does not 😢 I'll have to see if I can get around that somehow, otherwise I'll have to use a different strategy.

**Comment by samcf** [comment]
The issue is that Firefox doesn't allow selectors to pass from the main document to a shadow root.

https://bugzilla.mozilla.org/show_bug.cgi?id=997362#c4

The fix is to flatten the selectors out, probably caused by 4741e19d8c92aea0af9b127746979452d0d7ac6c

**Comment by samcf** [comment]
Fixed with cbf4615

**Comment by aetriusgx** [comment]
Hi I'm a player, not a DM, but I've been having this problem since our campaign began (around May 2024) and have had this issue since. I don't get this issue on Chromium browsers, just Firefox and Zen (firefox-based). 

Is there a workaround or can this be investigated further? I know it's likely out of your hands as mentioned before Firefox just has different rules for styling.

**Comment by samcf** [comment]
@aetriusgx this shouldn't be a problem anymore, token images seem to work fine for me in Chrome, Firefox, and Safari. Is it possible you're using an older version of the app? Let me know what version you're on, with a screenshot if possible, so I can help debug your issue.
