### ISSUE TITLE
Scene image not appearing on hosted site, but works locally

### ISSUE THREAD

**Issue by TorranceYang** [samcf/ogres#147]
Hi, love this project! 

I'm setting up a scene with a reasonably sized (2.8MB) JPEG background image I got from Reddit (https://www.reddit.com/r/mattcolville/comments/hpvhtg/oc_battlemap_the_delian_tomb/) and am having trouble when I create a public link and attempt to access it. 

The image loads in my local playground no problem, but as soon as I try connecting in an incognito window, tokens will load in for a second but then my client connection emits a failure to connect error. I don't really see an error on the host's side other than the status moving to `Disconnected`. 

I spun up a local server on my machine and using the same image works without issue. I don't think I'm hitting the size limit of 8-10MB, I wonder if there's something up with the hosted server.

Thanks!

**Comment by samcf** [comment]
Sorry about the delay, was on vacation! Let me take a look at this soon. I tested this on https://ogres.app/ with that image and it indeed crashes the local session - I'm assuming its because its too big to be transferred, but let me dig into this tomorrow when I have some free time.

**Comment by samcf** [comment]
Looking at logs and it looks like the server ran out of memory 😬 I've restarted the server so it should be OK now but will have to investigate for memory leaks.
